version: '3'

services:
  air-receiver:
    build: ./receiver
    env_file:
      - .env
    ports:
      - "${AIRRECEIVER_DIMSE}:11112"
    volumes:
      - ${AIRRECEIVER_PATH}:/app/dcmstore
    deploy:
      resources:
        limits:
          cpus: ${AIRRECEIVER_CPUS}
          memory: ${AIRRECEIVER_MEMORY}
